version: 2
jobs:
  build:
    branches:
      only:
        - main
    docker:
      # This docker image is created from the Dockerfile in
      # this repository.
      - image: ministryofjustice/cloud-platform-runbooks:1.7

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            # this SSH key must be configured in the account of the github user
            # who will be pushing changes. The corresponding private key must
            # be added to the project on circleci.com
            # Currently, this is the 'cloud-platform-moj' github user account.
            # The GitHub user must be added to the cloud-platform-user-guide
            # repository as an admin.
            - "0a:2d:c5:64:7e:e8:c5:d3:89:78:f9:ac:eb:91:32:2d"

      - checkout

        # Build the user guide
      - run: mkdir runbooks/compiled || true
      - run: cd runbooks; bin/add_source_url
      - run: cd runbooks; bundle exec middleman build --build-dir compiled

        # Replace compiled/.nojekyll (which gets deleted during the build process) so github knows we're
        # not using jekyll. Without this, github will try to process our files, and error.
      - run: touch runbooks/compiled/.nojekyll

        # Run the script to push the compiled files to the 'runbooks' github pages
        # repository
      - run: runbooks/bin/publish
