name: Check for broken links

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "source/**"

jobs:
  check_links:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:1.5
    steps:
    - uses: actions/checkout@v3
    - name: htmlproofer
      run: /publishing-scripts/publish.sh no-repository-changes
