name: Add dependencies to Cloud Platform project

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  add-dependabot-to-project:
    uses: ministryofjustice/cloud-platform-github-workflows/.github/workflows/dependencies-project.yml@61205bd138bba137d94df71e2b58af1955e537cf #main
    secrets: inherit
