name: Code-Formatter

on:
  push:
    branches: [test-workflow]
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    uses: ./.github/workflows/code-formatter/actions.yml
    secrets: inherit
