name: Publish runbooks
on:
  workflow_dispatch:
  push:
    branches:
      - "main"


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: github-pages
      cancel-in-progress: false
    container:
      image: ghcr.io/ministryofjustice/tech-docs-github-pages-publisher@sha256:8b00235edfa4d1248e3cdd08c022d5f398c7f4abb3315b6078f1e876214a171e # v6.2.0
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 # cant upgrade until tech-docs-github-pages-publisher image is updated
        
      - name: Compile Markdown to HTML and create artifact
        run: |
          cd runbooks; /scripts/deploy.sh false
          
      - name: Install rsync
        run: |
          apk update && apk add rsync
          which rsync

      - name: Configure Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5

      - name: Prepare Pages content
        run: |
          rsync -av --delete --exclude CNAME --exclude License --exclude README.md runbooks/docs/ pages/

      - name: Create Archive
        run: |
          tar --dereference --directory pages -cvf artifact.tar --exclude=.git --exclude=.github .

      - name: Upload Artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: github-pages
          path: artifact.tar
          retention-days: 1
          overwrite: true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
