name: Test publish runbooks
on:
  workflow_dispatch:
  push:
    tags:
      - "dependencies"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: github-pages
      cancel-in-progress: false
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:v3.0.2
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 # cant upgrade until tech-docs-github-pages-publisher image is updated
      - name: Compile Markdown to HTML and create artifact
        run: |
          cd runbooks; /scripts/deploy.sh false
      - name: Install rsync
        run: |
          apk update && apk add rsync
          which rsync

      - name: Configure Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5

      - name: Prepare Pages content
        run: |
          rsync -av --delete --exclude CNAME --exclude License --exclude README.md runbooks/docs/ pages/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@0252fc4ba7626f0298f0cf00902a25c6afc77fa8 # v3
        with:
          path: pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4